name: zagel
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  buttons_tabbar: ^1.3.15
  carousel_slider: ^5.0.0
  control_style: ^0.1.0
  custom_sliding_segmented_control: ^1.8.5
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.4.0
  slide_to_act: ^2.0.2
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
